import './App.css';
import React, { useState } from 'react';
import Spisok from './spisok';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";

function App() {
  const [json, setJson] = useState([
    { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' },
    { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' }, { name: 'Максим', lastName: 'Арсентьев', group: 'Руководство' },
    { name: 'Людмилла', lastName: 'Пономарёва', group: 'Руководство' },
    { name: 'Анастасия', lastName: 'Карандашева', group: 'Отдел кадров' },
    { name: 'Марина', lastName: 'Пулькина', group: 'Бухгалтерия' },
    { name: 'Дарья', lastName: 'Миронова', group: 'Отдел кадров' },
    { name: 'Андрей', lastName: 'Антошин', group: 'Отдел кадров' },
    { name: 'Леонид', lastName: 'Попов', group: 'Отдел кадров' },
    { name: 'Сергей', lastName: 'Арышев', group: 'Бухгалтерия' },
    { name: 'Степан', lastName: 'Голышев', group: 'Бухгалтерия' },
    { name: 'Дмитрий', lastName: 'Серов', group: 'Бухгалтерия' },
    { name: 'Анастасия', lastName: 'Печорина', group: 'Бухгалтерия' },

  ]);
  function addPersons(name, lastName, group) {
    setJson(json.concat([{
      name: name,
      lastName: lastName,
      group: group
    }]))
  }

  return (
    <>
      <Router>
        <nav style={{ textAlign: "right", marginRight: "25px" }}>
          <Link to="/">Главная</Link>
        &nbsp;
        <Link to="/spisok">Список</Link>
        </nav>
        <Switch>
          <Route path="/spisok">
            <Spisok info={json} add={addPersons} />
          </Route>
          <Route path="/">
            <h1 style={{ textAlign: 'center' }}>Поиск и сортировка сотрудников</h1>
          </Route>
        </Switch>
      </Router>
    </>
  );
}

export default App;
